// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"database/sql"
)

type Dataset struct {
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
