// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitestore

import (
	"database/sql"
)

type Datapoint struct {
	ID           int64
	DatarangeID  int64
	DatapointKey int64
	BeginOffset  int64
	EndOffset    int64
}

type Datarange struct {
	ID              int64
	DatasetName     string
	ObjectKey       string
	MinDatapointKey int64
	MaxDatapointKey int64
	SizeBytes       int64
}

type Dataset struct {
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
