name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run tests
        # Some tests fail on the runner, but because they're not relevant to our work, we disable them.
        run: nix develop --command go test ./...
